/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    homepage: Homepage;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage website images and bilingual image metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Internal label used to identify this image in the Media Library.
   */
  internalTitle?: string | null;
  /**
   * Required for the currently selected locale. Describe the image for accessibility; do not repeat decorative text.
   */
  alt: string;
  /**
   * Optional public-facing caption for the selected locale.
   */
  caption?: string | null;
  /**
   * Photographer, creator, or source credit.
   */
  credit?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  folder?: ('homepage' | 'projects' | 'clients' | 'stories' | 'team' | 'general') | null;
  /**
   * Internal notes about licensing, approved usage, or replacement.
   */
  usageNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  internalTitle?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  folder?: T;
  usageNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage fixed homepage sections. Layout, styling, animation, and component types remain code-owned.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  seo?: {
    /**
     * Recommended maximum: 60–70 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended maximum: 155–170 characters.
     */
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    /**
     * Optional absolute HTTP(S) canonical URL.
     */
    canonicalURL?: string | null;
  };
  hero: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    mediaType: 'image' | 'externalVideo';
    backgroundImage?: (number | null) | Media;
    posterImage?: (number | null) | Media;
    /**
     * External HTTP(S) URL only. Video uploads are not supported.
     */
    externalVideoURL?: string | null;
    primaryCTA?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    secondaryCTA?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    showScrollIndicator?: boolean | null;
  };
  about?: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    highlightText?: string | null;
    mainImage?: (number | null) | Media;
    gallery?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    cta?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
  };
  featuredProjects?: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Temporary embedded project cards. A later phase can replace this source with Project relationships.
     */
    items?:
      | {
          internalName: string;
          title: string;
          subtitle?: string | null;
          categoryLabel?: string | null;
          clientName?: string | null;
          year?: number | null;
          coverImage: number | Media;
          previewImage?: (number | null) | Media;
          /**
           * Optional YouTube, Vimeo, or other external HTTP(S) video URL.
           */
          externalVideoURL?: string | null;
          link: string;
          openInNewTab?: boolean | null;
          /**
           * Disabled content remains in the CMS but should not be rendered.
           */
          enabled?: boolean | null;
          /**
           * Lower values appear first. Array drag order remains available in Admin.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  projectCategories?: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Temporary homepage category cards; this does not create a Categories collection.
     */
    items?:
      | {
          internalName: string;
          title: string;
          description?: string | null;
          coverImage: number | Media;
          link: string;
          openInNewTab?: boolean | null;
          /**
           * Disabled content remains in the CMS but should not be rendered.
           */
          enabled?: boolean | null;
          /**
           * Lower values appear first. Array drag order remains available in Admin.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          internalName: string;
          title: string;
          description?: string | null;
          iconKey?: ('video' | 'camera' | 'editing' | 'drone' | 'event' | 'creative' | 'social' | 'livestream') | null;
          image?: (number | null) | Media;
          link?: string | null;
          /**
           * Disabled content remains in the CMS but should not be rendered.
           */
          enabled?: boolean | null;
          /**
           * Lower values appear first. Array drag order remains available in Admin.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  statistics?: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          value: number;
          prefix?: string | null;
          suffix?: string | null;
          label: string;
          /**
           * Disabled content remains in the CMS but should not be rendered.
           */
          enabled?: boolean | null;
          /**
           * Lower values appear first. Array drag order remains available in Admin.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  clients?: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          name: string;
          /**
           * Prefer a transparent PNG or WebP with sufficient contrast.
           */
          logo: number | Media;
          websiteURL?: string | null;
          /**
           * Disabled content remains in the CMS but should not be rendered.
           */
          enabled?: boolean | null;
          /**
           * Lower values appear first. Array drag order remains available in Admin.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  stories?: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Temporary embedded stories. A later phase can replace this source with Post relationships.
     */
    items?:
      | {
          internalName: string;
          title: string;
          excerpt?: string | null;
          thumbnail: number | Media;
          publishedDate?: string | null;
          link: string;
          openInNewTab?: boolean | null;
          /**
           * Disabled content remains in the CMS but should not be rendered.
           */
          enabled?: boolean | null;
          /**
           * Lower values appear first. Array drag order remains available in Admin.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  contactCTA?: {
    /**
     * Disabled content remains in the CMS but should not be rendered.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    backgroundImage?: (number | null) | Media;
    cta?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage website logos, navigation, language switcher, and header CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  branding?: {
    logoLight?: (number | null) | Media;
    logoDark?: (number | null) | Media;
    sticky?: boolean | null;
    transparentOnHero?: boolean | null;
    showLanguageSwitcher?: boolean | null;
  };
  navigation?: {
    /**
     * Use relative paths for internal pages and HTTP(S) URLs externally.
     */
    items?:
      | {
          internalName: string;
          label: string;
          url: string;
          openInNewTab?: boolean | null;
          /**
           * Disabled content remains in the CMS but should not be rendered.
           */
          enabled?: boolean | null;
          /**
           * Lower values appear first. Array drag order remains available in Admin.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    button?: {
      /**
       * Disabled content remains in the CMS but should not be rendered.
       */
      enabled?: boolean | null;
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage footer branding, localized navigation, contact details, and copyright.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  branding?: {
    logo?: (number | null) | Media;
    shortDescription?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  navigation?: {
    columns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                url: string;
                openInNewTab?: boolean | null;
                /**
                 * Disabled content remains in the CMS but should not be rendered.
                 */
                enabled?: boolean | null;
                /**
                 * Lower values appear first. Array drag order remains available in Admin.
                 */
                displayOrder: number;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  legal?: {
    copyright?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage public brand defaults, contact information, social links, SEO defaults, and maintenance messaging. Never store secrets here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    siteName: string;
    legalName?: string | null;
    defaultLocale: 'vi' | 'en';
    /**
     * Read-only mirror of the Payload fallback locale.
     */
    fallbackLocale: 'vi';
    favicon?: (number | null) | Media;
    defaultOGImage?: (number | null) | Media;
    logoMark?: (number | null) | Media;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  social?: {
    /**
     * Canonical social links. Do not duplicate these in Header or Footer.
     */
    socialLinks?:
      | {
          platform: 'facebook' | 'instagram' | 'tiktok' | 'youtube' | 'vimeo' | 'linkedin' | 'behance' | 'other';
          label?: string | null;
          url: string;
          /**
           * Disabled content remains in the CMS but should not be rendered.
           */
          enabled?: boolean | null;
          /**
           * Lower values appear first. Array drag order remains available in Admin.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  seoDefaults?: {
    defaultMetaTitle?: string | null;
    defaultMetaDescription?: string | null;
  };
  system?: {
    maintenanceMode?: boolean | null;
    maintenanceMessage?: string | null;
    defaultContactCTAURL?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        canonicalURL?: T;
      };
  hero?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        mediaType?: T;
        backgroundImage?: T;
        posterImage?: T;
        externalVideoURL?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        showScrollIndicator?: T;
      };
  about?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        highlightText?: T;
        mainImage?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
      };
  featuredProjects?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              internalName?: T;
              title?: T;
              subtitle?: T;
              categoryLabel?: T;
              clientName?: T;
              year?: T;
              coverImage?: T;
              previewImage?: T;
              externalVideoURL?: T;
              link?: T;
              openInNewTab?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  projectCategories?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              internalName?: T;
              title?: T;
              description?: T;
              coverImage?: T;
              link?: T;
              openInNewTab?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              internalName?: T;
              title?: T;
              description?: T;
              iconKey?: T;
              image?: T;
              link?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  statistics?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              value?: T;
              prefix?: T;
              suffix?: T;
              label?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  clients?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              logo?: T;
              websiteURL?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  stories?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              internalName?: T;
              title?: T;
              excerpt?: T;
              thumbnail?: T;
              publishedDate?: T;
              link?: T;
              openInNewTab?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  contactCTA?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        email?: T;
        phone?: T;
        address?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logoLight?: T;
        logoDark?: T;
        sticky?: T;
        transparentOnHero?: T;
        showLanguageSwitcher?: T;
      };
  navigation?:
    | T
    | {
        items?:
          | T
          | {
              internalName?: T;
              label?: T;
              url?: T;
              openInNewTab?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        button?:
          | T
          | {
              enabled?: T;
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logo?: T;
        shortDescription?: T;
        backgroundImage?: T;
      };
  navigation?:
    | T
    | {
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                    enabled?: T;
                    displayOrder?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  legal?:
    | T
    | {
        copyright?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        siteName?: T;
        legalName?: T;
        defaultLocale?: T;
        fallbackLocale?: T;
        favicon?: T;
        defaultOGImage?: T;
        logoMark?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  social?:
    | T
    | {
        socialLinks?:
          | T
          | {
              platform?: T;
              label?: T;
              url?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  seoDefaults?:
    | T
    | {
        defaultMetaTitle?: T;
        defaultMetaDescription?: T;
      };
  system?:
    | T
    | {
        maintenanceMode?: T;
        maintenanceMessage?: T;
        defaultContactCTAURL?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}