/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'project-categories': ProjectCategory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    homepage: Homepage;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Vai trò cố định của tài khoản quản trị duy nhất.
   */
  role: 'super-admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Tải lên và quản lý ảnh website cùng metadata song ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Nhãn nội bộ giúp nhận diện ảnh trong thư viện.
   */
  internalTitle?: string | null;
  /**
   * Bắt buộc cho ngôn ngữ đang chọn. Mô tả nội dung ảnh để hỗ trợ khả năng tiếp cận; không lặp lại chữ trang trí.
   */
  alt: string;
  /**
   * Chú thích hiển thị công khai cho ngôn ngữ đang chọn, không bắt buộc.
   */
  caption?: string | null;
  /**
   * Tên nhiếp ảnh gia, người sáng tạo hoặc nguồn ảnh.
   */
  credit?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  folder?: ('homepage' | 'projects' | 'clients' | 'stories' | 'team' | 'general') | null;
  /**
   * Ghi chú nội bộ về bản quyền, phạm vi sử dụng hoặc việc thay thế ảnh.
   */
  usageNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Nội dung dự án có cấu trúc và hỗ trợ song ngữ cho website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Nhãn dùng trong CMS; không hiển thị trên website public.
   */
  internalName: string;
  title: string;
  /**
   * Dùng chung cho URL tiếng Việt và tiếng Anh. Được tạo khi thêm mới và không tự đổi về sau. Sửa slug đã xuất bản có thể làm hỏng liên kết cũ.
   */
  slug: string;
  subtitle?: string | null;
  shortDescription: string;
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  clientName?: string | null;
  artistName?: string | null;
  year?: number | null;
  projectDate?: string | null;
  location?: string | null;
  primaryCategory: number | ProjectCategory;
  /**
   * Tối đa 5; không chọn lại danh mục chính.
   */
  secondaryCategories?: (number | ProjectCategory)[] | null;
  services?:
    | {
        /**
         * Nhãn dùng trong CMS; không hiển thị trên website public.
         */
        internalName: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  coverImage: number | Media;
  posterImage?: (number | null) | Media;
  /**
   * Dán URL YouTube, Vimeo hoặc tệp .mp4/.webm. Trên desktop video sẽ tự chạy, tắt tiếng và lặp lại khi rê chuột; nên ưu tiên MP4/WebM ngắn, đã tối ưu.
   */
  hoverPreviewVideoURL?: string | null;
  heroMediaType: 'image' | 'externalVideo';
  heroImage?: (number | null) | Media;
  /**
   * Chỉ dùng URL YouTube, Vimeo, tệp .mp4 hoặc .webm.
   */
  externalVideoURL?: string | null;
  videoPoster?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        /**
         * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
         */
        displayOrder: number;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  projectFacts?:
    | {
        label: string;
        value: string;
        /**
         * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
         */
        displayOrder: number;
        id?: string | null;
      }[]
    | null;
  statistics?:
    | {
        value: number;
        prefix?: string | null;
        suffix?: string | null;
        label: string;
        /**
         * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
         */
        displayOrder: number;
        id?: string | null;
      }[]
    | null;
  content?:
    | (
        | {
            internalName?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            maxWidth: 'narrow' | 'normal' | 'wide';
            textAlign: 'left' | 'center';
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            altOverride?: string | null;
            caption?: string | null;
            credit?: string | null;
            aspectRatio: 'original' | 'landscape' | 'cinematic' | 'portrait';
            containOrCover: 'cover' | 'contain';
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullWidthImage';
          }
        | {
            leftImage: number | Media;
            rightImage: number | Media;
            leftCaption?: string | null;
            rightCaption?: string | null;
            ratio: 'equal' | 'left-large' | 'right-large';
            mobileOrder: 'left-first' | 'right-first';
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnImages';
          }
        | {
            title?: string | null;
            description?: string | null;
            layout: 'grid' | 'masonry' | 'filmstrip';
            columns: '2' | '3' | '4';
            images: {
              image: number | Media;
              caption?: string | null;
              /**
               * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
               */
              displayOrder: number;
              id?: string | null;
            }[];
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            title?: string | null;
            description?: string | null;
            /**
             * URL YouTube, Vimeo, tệp .mp4 hoặc .webm.
             */
            videoURL: string;
            posterImage: number | Media;
            autoplay?: boolean | null;
            muted?: boolean | null;
            loop?: boolean | null;
            controls?: boolean | null;
            aspectRatio: '16:9' | '9:16' | '1:1' | 'cinematic';
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'externalVideo';
          }
        | {
            quote: string;
            author?: string | null;
            role?: string | null;
            portrait?: (number | null) | Media;
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            source: 'useProjectFacts' | 'custom';
            customFacts?:
              | {
                  label: string;
                  value: string;
                  /**
                   * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
                   */
                  displayOrder: number;
                  id?: string | null;
                }[]
              | null;
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectFacts';
          }
        | {
            source: 'useProjectStatistics' | 'custom';
            customItems?:
              | {
                  value: number;
                  prefix?: string | null;
                  suffix?: string | null;
                  label: string;
                  /**
                   * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
                   */
                  displayOrder: number;
                  id?: string | null;
                }[]
              | null;
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image: number | Media;
            imagePosition: 'left' | 'right';
            verticalAlignment: 'top' | 'center' | 'bottom';
            backgroundStyle: 'default' | 'surface' | 'brand-accent';
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textImage';
          }
        | {
            title?: string | null;
            mode: 'automatic' | 'manual';
            manualProjects?: (number | Project)[] | null;
            maxItems: number;
            automaticStrategy?: ('samePrimaryCategory' | 'sharedCategories' | 'featured') | null;
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedProjects';
          }
      )[]
    | null;
  /**
   * Chỉ dùng dữ liệu thẻ; dự án hiện tại đã được loại trừ.
   */
  relatedProjects?: (number | Project)[] | null;
  seo?: {
    /**
     * Khuyến nghị tối đa 60–70 ký tự.
     */
    metaTitle?: string | null;
    /**
     * Khuyến nghị tối đa 155–170 ký tự.
     */
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    /**
     * URL HTTP(S) chính tắc đầy đủ, không bắt buộc.
     */
    canonicalURL?: string | null;
  };
  featured?: boolean | null;
  featuredOrder?: number | null;
  /**
   * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
   */
  enabled?: boolean | null;
  /**
   * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
   */
  displayOrder: number;
  /**
   * Chỉ dùng nội bộ; không trả về qua helper public.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Hệ thống phân loại dự án song ngữ. Trạng thái xuất bản dùng chung cho vi và en.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  /**
   * Nhãn dùng trong CMS; không hiển thị trên website public.
   */
  internalName: string;
  title: string;
  /**
   * Dùng chung cho URL tiếng Việt và tiếng Anh. Được tạo khi thêm mới và không tự đổi về sau. Sửa slug đã xuất bản có thể làm hỏng liên kết cũ.
   */
  slug: string;
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  iconKey?:
    | (
        | 'event'
        | 'corporate'
        | 'sports'
        | 'social'
        | 'artist'
        | 'automotive'
        | 'travel'
        | 'beauty'
        | 'behind-the-scenes'
      )
    | null;
  coverImage: number | Media;
  heroImage?: (number | null) | Media;
  /**
   * URL YouTube, Vimeo, tệp .mp4 hoặc .webm; không bắt buộc.
   */
  heroVideoURL?: string | null;
  seo?: {
    /**
     * Khuyến nghị tối đa 60–70 ký tự.
     */
    metaTitle?: string | null;
    /**
     * Khuyến nghị tối đa 155–170 ký tự.
     */
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    /**
     * URL HTTP(S) chính tắc đầy đủ, không bắt buộc.
     */
    canonicalURL?: string | null;
  };
  /**
   * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
   */
  enabled?: boolean | null;
  featured?: boolean | null;
  /**
   * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
   */
  displayOrder: number;
  /**
   * Chỉ dùng nội bộ; không trả về qua helper public.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  internalTitle?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  folder?: T;
  usageNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  internalName?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  shortDescription?: T;
  introduction?: T;
  clientName?: T;
  artistName?: T;
  year?: T;
  projectDate?: T;
  location?: T;
  primaryCategory?: T;
  secondaryCategories?: T;
  services?:
    | T
    | {
        internalName?: T;
        label?: T;
        id?: T;
      };
  coverImage?: T;
  posterImage?: T;
  hoverPreviewVideoURL?: T;
  heroMediaType?: T;
  heroImage?: T;
  externalVideoURL?: T;
  videoPoster?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        displayOrder?: T;
        credit?: T;
        id?: T;
      };
  projectFacts?:
    | T
    | {
        label?: T;
        value?: T;
        displayOrder?: T;
        id?: T;
      };
  statistics?:
    | T
    | {
        value?: T;
        prefix?: T;
        suffix?: T;
        label?: T;
        displayOrder?: T;
        id?: T;
      };
  content?:
    | T
    | {
        richText?:
          | T
          | {
              internalName?: T;
              content?: T;
              maxWidth?: T;
              textAlign?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        fullWidthImage?:
          | T
          | {
              image?: T;
              altOverride?: T;
              caption?: T;
              credit?: T;
              aspectRatio?: T;
              containOrCover?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        twoColumnImages?:
          | T
          | {
              leftImage?: T;
              rightImage?: T;
              leftCaption?: T;
              rightCaption?: T;
              ratio?: T;
              mobileOrder?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              title?: T;
              description?: T;
              layout?: T;
              columns?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    displayOrder?: T;
                    id?: T;
                  };
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        externalVideo?:
          | T
          | {
              title?: T;
              description?: T;
              videoURL?: T;
              posterImage?: T;
              autoplay?: T;
              muted?: T;
              loop?: T;
              controls?: T;
              aspectRatio?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              author?: T;
              role?: T;
              portrait?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        projectFacts?:
          | T
          | {
              source?: T;
              customFacts?:
                | T
                | {
                    label?: T;
                    value?: T;
                    displayOrder?: T;
                    id?: T;
                  };
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              source?: T;
              customItems?:
                | T
                | {
                    value?: T;
                    prefix?: T;
                    suffix?: T;
                    label?: T;
                    displayOrder?: T;
                    id?: T;
                  };
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        textImage?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              verticalAlignment?: T;
              backgroundStyle?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        relatedProjects?:
          | T
          | {
              title?: T;
              mode?: T;
              manualProjects?: T;
              maxItems?: T;
              automaticStrategy?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
      };
  relatedProjects?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        canonicalURL?: T;
      };
  featured?: T;
  featuredOrder?: T;
  enabled?: T;
  displayOrder?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  internalName?: T;
  title?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  iconKey?: T;
  coverImage?: T;
  heroImage?: T;
  heroVideoURL?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        canonicalURL?: T;
      };
  enabled?: T;
  featured?: T;
  displayOrder?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Quản lý nội dung các section cố định. Bố cục, giao diện, animation và loại component vẫn do source code kiểm soát.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  seo?: {
    /**
     * Khuyến nghị tối đa 60–70 ký tự.
     */
    metaTitle?: string | null;
    /**
     * Khuyến nghị tối đa 155–170 ký tự.
     */
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    /**
     * URL HTTP(S) chính tắc đầy đủ, không bắt buộc.
     */
    canonicalURL?: string | null;
  };
  hero: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    mediaType: 'image' | 'externalVideo';
    backgroundImage?: (number | null) | Media;
    posterImage?: (number | null) | Media;
    /**
     * Chỉ dùng URL HTTP(S) bên ngoài. Không hỗ trợ tải video lên.
     */
    externalVideoURL?: string | null;
    primaryCTA?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    secondaryCTA?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    showScrollIndicator?: boolean | null;
  };
  about?: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    highlightText?: string | null;
    mainImage?: (number | null) | Media;
    gallery?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    cta?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
  };
  featuredProjects: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Chọn nhập thẻ thủ công hoặc lấy dữ liệu từ collection Dự án.
     */
    sourceMode: 'manualEmbedded' | 'projectCollection';
    selectedProjects?: (number | Project)[] | null;
    collectionLimit?: number | null;
    collectionFilterFeatured?: boolean | null;
    /**
     * Các thẻ dự án nhập trực tiếp; chỉ dùng khi nguồn dữ liệu là thủ công.
     */
    items?:
      | {
          internalName: string;
          title: string;
          subtitle?: string | null;
          categoryLabel?: string | null;
          clientName?: string | null;
          year?: number | null;
          coverImage: number | Media;
          previewImage?: (number | null) | Media;
          /**
           * URL HTTP(S) của YouTube, Vimeo hoặc nguồn video khác; không bắt buộc.
           */
          externalVideoURL?: string | null;
          link: string;
          openInNewTab?: boolean | null;
          /**
           * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
           */
          enabled?: boolean | null;
          /**
           * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  projectCategories: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Chọn nhập thẻ thủ công hoặc lấy dữ liệu từ collection Danh mục dự án.
     */
    sourceMode: 'manualEmbedded' | 'categoryCollection';
    selectedCategories?: (number | ProjectCategory)[] | null;
    collectionLimit?: number | null;
    /**
     * Các thẻ danh mục nhập trực tiếp; chỉ dùng khi nguồn dữ liệu là thủ công.
     */
    items?:
      | {
          internalName: string;
          title: string;
          description?: string | null;
          coverImage: number | Media;
          link: string;
          openInNewTab?: boolean | null;
          /**
           * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
           */
          enabled?: boolean | null;
          /**
           * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          internalName: string;
          title: string;
          description?: string | null;
          iconKey?: ('video' | 'camera' | 'editing' | 'drone' | 'event' | 'creative' | 'social' | 'livestream') | null;
          image?: (number | null) | Media;
          link?: string | null;
          /**
           * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
           */
          enabled?: boolean | null;
          /**
           * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  statistics?: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          value: number;
          prefix?: string | null;
          suffix?: string | null;
          label: string;
          /**
           * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
           */
          enabled?: boolean | null;
          /**
           * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  clients?: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          name: string;
          /**
           * Ưu tiên PNG hoặc WebP nền trong suốt và có độ tương phản phù hợp.
           */
          logo: number | Media;
          websiteURL?: string | null;
          /**
           * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
           */
          enabled?: boolean | null;
          /**
           * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  stories?: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Danh sách câu chuyện nhập trực tiếp; có thể chuyển sang collection Bài viết ở phase sau.
     */
    items?:
      | {
          internalName: string;
          title: string;
          excerpt?: string | null;
          thumbnail: number | Media;
          publishedDate?: string | null;
          link: string;
          openInNewTab?: boolean | null;
          /**
           * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
           */
          enabled?: boolean | null;
          /**
           * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  contactCTA?: {
    /**
     * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
     */
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    backgroundImage?: (number | null) | Media;
    cta?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Quản lý logo, điều hướng, nút chuyển ngôn ngữ và CTA ở đầu trang.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  branding?: {
    logoLight?: (number | null) | Media;
    logoDark?: (number | null) | Media;
    sticky?: boolean | null;
    transparentOnHero?: boolean | null;
    showLanguageSwitcher?: boolean | null;
  };
  navigation?: {
    /**
     * Dùng đường dẫn tương đối cho trang nội bộ và URL HTTP(S) cho liên kết ngoài.
     */
    items?:
      | {
          internalName: string;
          label: string;
          url: string;
          openInNewTab?: boolean | null;
          /**
           * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
           */
          enabled?: boolean | null;
          /**
           * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    button?: {
      /**
       * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
       */
      enabled?: boolean | null;
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Quản lý thương hiệu, điều hướng song ngữ, thông tin liên hệ và bản quyền ở chân trang.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  branding?: {
    logo?: (number | null) | Media;
    shortDescription?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  navigation?: {
    columns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                url: string;
                openInNewTab?: boolean | null;
                /**
                 * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
                 */
                enabled?: boolean | null;
                /**
                 * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
                 */
                displayOrder: number;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    /**
     * Nếu để trống, hệ thống sẽ tự động hiển thị Google Maps theo trường Địa chỉ ở trên.
     */
    mapEmbedUrl?: string | null;
  };
  legal?: {
    copyright?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Quản lý thương hiệu, liên hệ, mạng xã hội, SEO mặc định và thông báo bảo trì. Không lưu secret tại đây.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    siteName: string;
    legalName?: string | null;
    defaultLocale: 'vi' | 'en';
    /**
     * Giá trị chỉ đọc, phản ánh locale dự phòng của Payload.
     */
    fallbackLocale: 'vi';
    favicon?: (number | null) | Media;
    defaultOGImage?: (number | null) | Media;
    logoMark?: (number | null) | Media;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  social?: {
    /**
     * Danh sách mạng xã hội dùng chung. Không nhập trùng trong Header hoặc Footer.
     */
    socialLinks?:
      | {
          platform:
            | 'facebook'
            | 'instagram'
            | 'tiktok'
            | 'zalo'
            | 'youtube'
            | 'vimeo'
            | 'linkedin'
            | 'behance'
            | 'other';
          label?: string | null;
          url: string;
          /**
           * Nội dung bị tắt vẫn được giữ trong CMS nhưng không hiển thị ngoài website.
           */
          enabled?: boolean | null;
          /**
           * Số nhỏ hơn hiển thị trước. Vẫn có thể kéo thả item trong danh sách.
           */
          displayOrder: number;
          id?: string | null;
        }[]
      | null;
  };
  seoDefaults?: {
    defaultMetaTitle?: string | null;
    defaultMetaDescription?: string | null;
  };
  system?: {
    maintenanceMode?: boolean | null;
    maintenanceMessage?: string | null;
    defaultContactCTAURL?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        canonicalURL?: T;
      };
  hero?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        mediaType?: T;
        backgroundImage?: T;
        posterImage?: T;
        externalVideoURL?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        showScrollIndicator?: T;
      };
  about?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        highlightText?: T;
        mainImage?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
      };
  featuredProjects?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        sourceMode?: T;
        selectedProjects?: T;
        collectionLimit?: T;
        collectionFilterFeatured?: T;
        items?:
          | T
          | {
              internalName?: T;
              title?: T;
              subtitle?: T;
              categoryLabel?: T;
              clientName?: T;
              year?: T;
              coverImage?: T;
              previewImage?: T;
              externalVideoURL?: T;
              link?: T;
              openInNewTab?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  projectCategories?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        sourceMode?: T;
        selectedCategories?: T;
        collectionLimit?: T;
        items?:
          | T
          | {
              internalName?: T;
              title?: T;
              description?: T;
              coverImage?: T;
              link?: T;
              openInNewTab?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              internalName?: T;
              title?: T;
              description?: T;
              iconKey?: T;
              image?: T;
              link?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  statistics?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              value?: T;
              prefix?: T;
              suffix?: T;
              label?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  clients?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              logo?: T;
              websiteURL?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  stories?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              internalName?: T;
              title?: T;
              excerpt?: T;
              thumbnail?: T;
              publishedDate?: T;
              link?: T;
              openInNewTab?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  contactCTA?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        email?: T;
        phone?: T;
        address?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logoLight?: T;
        logoDark?: T;
        sticky?: T;
        transparentOnHero?: T;
        showLanguageSwitcher?: T;
      };
  navigation?:
    | T
    | {
        items?:
          | T
          | {
              internalName?: T;
              label?: T;
              url?: T;
              openInNewTab?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        button?:
          | T
          | {
              enabled?: T;
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logo?: T;
        shortDescription?: T;
        backgroundImage?: T;
      };
  navigation?:
    | T
    | {
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                    enabled?: T;
                    displayOrder?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        mapEmbedUrl?: T;
      };
  legal?:
    | T
    | {
        copyright?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        siteName?: T;
        legalName?: T;
        defaultLocale?: T;
        fallbackLocale?: T;
        favicon?: T;
        defaultOGImage?: T;
        logoMark?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  social?:
    | T
    | {
        socialLinks?:
          | T
          | {
              platform?: T;
              label?: T;
              url?: T;
              enabled?: T;
              displayOrder?: T;
              id?: T;
            };
      };
  seoDefaults?:
    | T
    | {
        defaultMetaTitle?: T;
        defaultMetaDescription?: T;
      };
  system?:
    | T
    | {
        maintenanceMode?: T;
        maintenanceMessage?: T;
        defaultContactCTAURL?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}